name: Test Code Quality with CodeClimate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code Climate Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Code Climate
        uses: erzz/codeclimate-standalone@v0
        with:
          html_report: true

      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Code Climate Report
          path: codeclimate-report.html