name: Jest-Puppeteer E2E Tests

on:
  pull_request
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - run: |
          npm ci
          npm run build
          npm run serve
          npm run e2e-test
