name: Mocha Unit Tests

on:
  pull_request:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - run: |
          npm ci
          npm run build
          npm run serve
          npm run test
